name: macOS_RDP

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Installer TeamViewer
      run: |
        brew install --cask teamviewer
    
    - name: Configurer le mot de passe TeamViewer
      run: |
        # On définit un mot de passe fixe pour TeamViewer
        sudo /Applications/TeamViewer.app/Contents/Helpers/TeamViewer_Service -passwd MonSuperMdp123!
    
    - name: Démarrer TeamViewer et afficher l'ID
      run: |
        # On lance TeamViewer
        open -a TeamViewer
        sleep 10
        # On récupère et on affiche l'ID de connexion dans les logs GitHub
        echo "==========================================="
        echo "VOTRE ID TEAMVIEWER EST :"
        defaults read /Library/Preferences/com.teamviewer.teamviewer.preferences.plist ClientID
        echo "MOT DE PASSE : MonSuperMdp123!"
        echo "==========================================="
    
    - name: Garder la machine allumée
      run: |
        # Cette ligne laisse le Mac tourner pendant 6 heures
        sleep 21600
