name: macOS_RDP

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Installer TeamViewer
      run: |
        brew install --cask teamviewer
    - name: Activer le Partage d'Écran macOS (VNC)
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/contents/Resources/kickstart -activate -configure -access -on -clientopts -setvncpasswd -vncpasswd MonSuperMdp123! -perms -all -restart -agent -privs -all
    - name: Lancer la connexion avec Pinggy
      run: |
        ssh -o StrictHostKeyChecking=no -p 443 -R 0:localhost:5900 a.pinggy.io
